### ISSUE TITLE
./blindspot-assistance  openvino

### ISSUE THREAD

**Issue by emadosama56** [incluit/OpenVino-Blindspot-Assistance#7]
./blindspot-assistance -m -l /home/ai-team/openvino_models/ir/intel/pedestrian-and-vehicle-detector-adas-0001/FP32/pedestrian-and-vehicle-detector-adas-0001.xml -d HETERO:CPU -i /home/ai-team/OpenVino-Driver-Behaviour/data/img_1.jpg

output
bash: ./blindspot-assistance: No such file or directory

**Comment by lfoIncluit** [comment]
Hi, can you give us information about the compilation process. Are you building it into docker?
